name: Deploy FastAPI to Windows Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker ps --filter "name=fastapi_app" -q | ForEach-Object { docker stop $_; docker rm $_ }
            docker images "my_fastapi_app" -q | ForEach-Object { docker rmi $_ }
            cd C:/path/to/deploy
            git pull
            docker build -t my_fastapi_app .
            docker run -d --name fastapi_app -p 8050:8050 my_fastapi_app
