name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Run Docker Container
        run: |
          docker ps -q --filter "name=fastapi_app" | xargs -r docker stop
          docker ps -a -q --filter "name=fastapi_app" | xargs -r docker rm
          docker images -q "my_fastapi_app" | xargs -r docker rmi
          docker build -t my_fastapi_app .
          docker run -d --name fastapi_app -p 8050:8050 my_fastapi_app

      - name: Verify Deployment
        run: curl -f http://localhost:8050 || echo "Deployment verification failed"
