name: Docker Deploy on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: narrativa_ml
      DOCKER_CONTAINER_NAME: narrativa_ml
      SERVER_IP: 192.168.0.204
      SERVER_USER: narrativa
      SERVER_PORT: 22

    steps:
      # 1. Git 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. DockerHub에 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. PowerShell을 사용하여 Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        shell: powershell
        run: |
          $dockerHubUsername = "${{ secrets.DOCKERHUB_USERNAME }}"
          $dockerImageName = "$dockerHubUsername/$($env:DOCKER_IMAGE_NAME):latest"
          
          Write-Host "DockerHub Username: $dockerHubUsername"
          Write-Host "Docker Image Name: $dockerImageName"
          
          # 변수 유효성 검사
          if (-not $dockerHubUsername) {
              Write-Error "DOCKERHUB_USERNAME이 설정되지 않았습니다"
              exit 1
          }

          if (-not $env:DOCKER_IMAGE_NAME) {
              Write-Error "DOCKER_IMAGE_NAME이 설정되지 않았습니다"
              exit 1
          }

          # Docker 이미지 빌드 및 푸시
          docker build -t $dockerImageName .
          docker push $dockerImageName

      # 4. SSH를 사용하여 원격 서버에 배포
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$($env:DOCKER_IMAGE_NAME):latest
            docker stop $DOCKER_CONTAINER_NAME || true
            docker rm $DOCKER_CONTAINER_NAME || true
            docker run -d --name $DOCKER_CONTAINER_NAME -p 8050:8050 ${{ secrets.DOCKERHUB_USERNAME }}/$($env:DOCKER_IMAGE_NAME):latest
