name: Deploy FastAPI to Windows Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if (docker ps --filter "name=fastapi_app" | Select-String "fastapi_app") { docker stop fastapi_app }
            if (docker ps -a --filter "name=fastapi_app" | Select-String "fastapi_app") { docker rm fastapi_app }
            if (docker images | Select-String "my_fastapi_app") { docker rmi my_fastapi_app }

            cd C:/path/to/deploy
            git pull

            docker build -t my_fastapi_app .
            docker run -d --name fastapi_app -p 8050:8050 my_fastapi_app
