name: Docker Deploy on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: stjoo0925/narrativa_ml
      DOCKER_CONTAINER_NAME: narrativa_ml
      SERVER_IP: 221.148.97.238
      SERVER_USER: narrativa
      SERVER_PORT: 8050

    steps:
      # 1. Git Repository Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker on the Runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4. Build Docker Image
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:latest .
          docker push $DOCKER_IMAGE_NAME:latest

      # 5. Deploy to Remote Server using SSH
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            docker pull $DOCKER_IMAGE_NAME:latest
            docker stop $DOCKER_CONTAINER_NAME || true
            docker rm $DOCKER_CONTAINER_NAME || true
            docker run -d --name $DOCKER_CONTAINER_NAME -p 8050:8050 $DOCKER_IMAGE_NAME:latest
