name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.8
  with:
    host: ${{ secrets.EC2_HOST_ML }}
    username: ec2-user
    key: ${{ secrets.EC2_PRIVATE_KEY_ML }}
    port: 22
    script: |
      # Git과 Docker Compose 설치 확인
      if ! [ -x "$(command -v git)" ]; then
        sudo yum install git -y || sudo apt install git -y
      fi
      if ! [ -x "$(command -v docker-compose)" ]; then
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      fi
      
      # 프로젝트 디렉토리 설정
      PROJECT_DIR="/home/ec2-user/project"
      
      # Git 클론 또는 pull
      if [ ! -d "${PROJECT_DIR}/.git" ]; then
        rm -rf ${PROJECT_DIR}
        mkdir -p ${PROJECT_DIR}
        git clone https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/AI-X-4-A1-FINAL/Narrativa_ML.git ${PROJECT_DIR}
      else
        cd ${PROJECT_DIR}
        git pull origin dev
      fi
      
      # Docker Compose 실행
      cd ${PROJECT_DIR}
      docker-compose -f ${PROJECT_DIR}/docker-compose.yml --env-file ${PROJECT_DIR}/.env down || true
      docker-compose -f ${PROJECT_DIR}/docker-compose.yml --env-file ${PROJECT_DIR}/.env up -d --build
