name: CI/CD for EC2 Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 3. Docker Compose 파일 유효성 검사
      - name: Validate Docker Compose file
        run: docker-compose config

      # 4. Docker 이미지 빌드
      - name: Build Docker image
        run: docker-compose build

      # 5. EC2 서버에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_ML }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY_ML }}
          port: 22
          script: |
            # 1. 프로젝트 디렉토리로 이동
            cd /home/ec2-user/project || exit

            # 2. 기존 컨테이너 종료 및 제거
            docker-compose down || true

            # 3. 최신 코드 가져오기
            git pull origin dev

            # 4. Docker Compose로 컨테이너 실행
            docker-compose up -d --build
