name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Python 설치
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. 의존성 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # 4. main.py에서 버전 추출
    - name: Extract version from main.py
      id: get_version
      run: |
        VERSION=$(grep -oP '__version__\s*=\s*"\K[^"]+' main.py)
        echo "version=$VERSION" >> $GITHUB_ENV

    # 5. GitHub 릴리스 생성
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ env.version }}
        name: Release v${{ env.version }}
        draft: false
        prerelease: false
        body: |
          ## New Release v${{ env.version }}
          - This release was automatically created from the main branch.
